### ISSUE TITLE
Jenkins guide on how to setup?

### ISSUE THREAD

**Issue by ghost** [Rudd-O/copperheados-build#6]
I've never used Jenkins and is there a guide on how to do this? I'm lost. How do I make the keys within Jenkins?

**Comment by noterminusgit** [comment]
You make the keys as part of the Copperhead build process.

The context for the instructions can be found here: https://copperhead.co/android/docs/building

**Comment by ghost** [comment]
Sorry, I mean like can I make the keys with Jenkins itself? I've gotten pretty far on VMWare but i'm on windows...

**Comment by noterminusgit** [comment]
You probably need a Linux install of Jenkins for this application to work,
because you'll need the build dependencies in addition to things like these
keys.

**Comment by ghost** [comment]
AHHH, okay this now makes so much more sense haha thank you.

**Comment by Rudd-O** [comment]
I am positive you can write a program that Jenkins can run which will
make the keys on every build.  Which will absolutely fuck up the whole
point of this, because now the keys change on every build... which means
your phone's bootloader will not accept firmware updates from subsequent
builds after you've installed the first build.  Oops.

Do as the README says.  Make the keys offline, copy them into the
Jenkins jobs directory as specified by the instructions, then run the
Jenkins job.

-- 
    Rudd-O
    http://rudd-o.com/
